### ISSUE TITLE
ijar fails because Frege loads classes of dependencies

### ISSUE THREAD

**Issue by johnynek** [johnynek/gottlob#1]
Frege to get the type signatures uses attributes on classes. If you try to use ijar (interface only jars with no code), this fails:

```
java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file Hello0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)                                                                                                 at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)                                                                                                     at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at frege.runtime.CompilerSupport.getFrege(CompilerSupport.java:16)
```
you can see that [method](https://github.com/Frege/frege/blob/398e5e8b88bf4141ce71228bd2458163f71581e3/frege/runtime/CompilerSupport.java#L13):
```java
  public static Meta.FregePackage getFrege(ClassLoader loader, String pack) 
		  throws ClassNotFoundException {
		Class<?> cl = null;
	    cl = loader.loadClass(pack);
		return cl.getAnnotation(Meta.FregePackage.class);
	}
```
since, ijars can't be loaded, this fails. I guess scalac and javac have their own parser rather than using a classloader.

**Comment by johnynek** [comment]
Would be nice to find a way to parse the annotations without loading the class. If we can do that and upstream the change, then we should be able to use ijar.
